### ISSUE TITLE
Blog should have Atom or RSS feed

### ISSUE THREAD

**Issue by schuster** [tokio-rs/website#10]
I just discovered the new Tokio website today and saw that there's an associated blog. I'd like to keep up with developments in Tokio, but it seems there's no Atom or RSS feed for the blog that would make that easy to do.

I don't know what that would take in Hugo to implement, so this is more of a "nice to have" than anything.

**Comment by alexcrichton** [comment]
I haven't used atom/rss too much, but is https://tokio.rs/blog/index.xml the feed you're looking for? If so, we may just be missing some meta tag or something to indicate that it exists.

**Comment by schuster** [comment]
Yep, just what I was looking for, thanks! Just submitted a PR to add the link so it's more discoverable.
