### ISSUE TITLE
tasks section: "on the current thread" doesn't explain that notify is never called

### ISSUE THREAD

**Issue by tamird** [tokio-rs/website#118]
This section doesn't explain that running a task that blocks (and thus returns NotReady) will deadlock when called with `.wait()`. This seems perfectly "obvious" and yet the absence of the explicit callout lead me to spend a bunch of time looking through the source and writing a test to convince myself that indeed this deadlocks:
```rust
#[test]
fn deadlock() {
    use std::time::{Duration,Instant};

    let start = Instant::now();
    println!("starting at {:?}!", &start);
    let future = future::poll_fn::<_, u32, _>(move || {
        let now = Instant::now();
        println!("being polled at {:?}!", &now);
        if now.duration_since(start) < Duration::from_secs(1) {
            Ok(Async::NotReady)
        } else {
            Ok(Async::Ready(1))
        }
    });
    assert_eq!(future.wait().unwrap(), 1)
}
```
It might be worth calling this out explicitly.

**Comment by Darksonn** [comment]
I am closing this as it is an issue about a guide that no longer exists.
