### ISSUE TITLE
No license for tokio-rs/website repository.

### ISSUE THREAD

**Issue by echochamber** [tokio-rs/website#124]
Not sure if I'm being thick or if there isn't a license file for this repo yet.

I have a small patch I'd like to make to fix a few incorrect links: some of the links in https://tokio.rs/docs/going-deeper-futures/tasks/ which are supposed to link to [futures::executor::spawn](https://docs.rs/futures/0.1/futures/executor/fn.spawn.html) are instead linking to [futures::executor::Spawn](https://docs.rs/futures/0.1/futures/executor/struct.Spawn.html) but I need the repository to add a license before I can open a PR.

**Comment by carllerche** [comment]
It's going to be a tad tricky to add a license now that there have been contributions. A license can be made for new contributions.

**Comment by carllerche** [comment]
Ok, I added a license for new contributions. Relicensing the repo is a work in progress (see #139). I'm going to close this now.

Thanks for the report!

**Comment by echochamber** [comment]
Sounds good. Thanks @carllerche
