### ISSUE TITLE
License under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/website#139]
The repository currently does not have an associated license, [preventing] some from contributing.

[preventing]: https://github.com/tokio-rs/website/issues/124

In order to fully relicense this repository, all contributors must sign-off.

You are receiving this notification because you have contributed to this repo.

While smaller changes can't be copyrighted by law, its non-trivial to find out with certainty whether a given change falls under copyright or not, due to the nature of the matter. Therefore I'm asking you to agree to the new terms even if you consider your contributions to be not copyrightable.

# Checkoff

To agree to the licensing terms, please comment with:

> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

Thank you!

* [x] @alexcrichton
* [x] @aturon
* [x] @carllerche
* [x] @nelsonjchen
* [x] @hockeybuggy
* [x] @rbalicki2
* [x] @shepmaster
* [x] @RadicalZephyr
* [ ] @munckymagik
* [x] @khaledkbadr
* [x] @funkill
* [x] @Rufflewind
* [x] @vi
* [x] @mbrubeck
* [x] @radupopescu
* [x] @irtefa
* [x] @SuperFluffy
* [x] @theduke
* [x] @Phrohdoh
* [x] @tafia
* [ ] @sheeldotme
* [x] @kanerogers
* [ ] @braddunbar
* [ ] @lazyval
* [ ] @toddWannaCode
* [x] @oconnor663
* [x] @mohammadsamir
* [ ] @hngnaig
* [x] @DirkyJerky
* [x] @mayhewj
* [x] @jasondavies
* [x] @DmitryBochkarev
* [x] @zmanian
* [x] @baloo
* [x] @schleumer
* [x] @jbendig
* [x] @mre
* [x] @dfockler
* [x] @ineol
* [x] @daschl
* [x] @srijs
* [x] @Freyskeyd
* [x] @danobi
* [x] @kw217
* [x] @AaronStGeorge
* [x] @jedisct1
* [x] @CrockAgile
* [x] @tanimoto
* [x] @awelkie
* [x] @matematikaadit
* [x] @rofrol
* [x] @jefflembeck
* [x] @mquandalle
* [x] @iamcodemaker
* [x] @zklapow
* [x] @schuster
* [x] @acobster
* [x] @cgwalters
* [x] @P-E-Meunier
* [x] @mgattozzi
* [x] @steveklabnik
* [x] @dwrensha
* [x] @redaready

**Comment by carllerche** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jasondavies** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by hockeybuggy** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by khaledkbadr** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Phrohdoh** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by oconnor663** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by schleumer** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by radupopescu** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mayhewj** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

On Feb 15, 2018, at 5:34 PM, Wesley Schleumer de Góes <notifications@github.com<mailto:notifications@github.com>> wrote:


I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by SuperFluffy** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by nelsonjchen** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by srijs** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

**Comment by zmanian** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

**Comment by shepmaster** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ineol** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mre** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by aturon** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by kw217** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by kanerogers** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

**Comment by vi** [comment]
I license past and future contributions to this repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by AaronStGeorge** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by CrockAgile** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by theduke** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by RadicalZephyr** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mbrubeck** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by tanimoto** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Rufflewind** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by tafia** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

On Feb 16, 2018 10:48, "Phil Ruffwind" <notifications@github.com> wrote:

I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

—

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tokio-rs/website/issues/139#issuecomment-366130543>,
or mute
the thread

**Comment by DmitryBochkarev** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by DirkyJerky** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

**Comment by funkill** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by daschl** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Freyskeyd** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by awelkie** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by irtefa** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

**Comment by dfockler** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by danobi** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by matematikaadit** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jbendig** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by baloo** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mohammadsamir** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by rbalicki2** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to chose either at their option.

**Comment by alexcrichton** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by dwrensha** [comment]
Word.

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jedisct1** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by steveklabnik** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by carllerche** [comment]
Ping!

@munckymagik @radupopescu @sheeldotme @braddunbar @lazyval @toddWannaCode @hngnaig @rofrol @jefflembeck @mquandalle @iamcodemaker @zklapow @schuster @acobster @cgwalters @p-e-meunier @mgattozzi @redaready

**Comment by cgwalters** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jefflembeck** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by radupopescu** [comment]
Hi,
I replied 20 days ago.
Cheers,

**Comment by acobster** [comment]
Sounds good to me! :)

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by iamcodemaker** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mgattozzi** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by schuster** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by P-E-Meunier** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mquandalle** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by carllerche** [comment]
@radupopescu Woops, sorry about that. Got you this time!

**Comment by rofrol** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by radupopescu** [comment]
@carllerche No worries! Cheers!

**Comment by zklapow** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by carllerche** [comment]
Ping: @munckymagik @sheeldotme @braddunbar @lazyval @toddWannaCode @hngnaig

**Comment by tobz** [comment]
Roll call! @munckymagik @sheeldotme @braddunbar @lazyval @toddWannaCode @hngnaig

**Comment by sheeldotme** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by carllerche** [comment]
Authors for all *existing* content on master have been covered by this issue. As such, I will close. Thanks all.
