### ISSUE TITLE
Add  Read-Timeout example 

### ISSUE THREAD

**Issue by frehberg** [tokio-rs/website#151]
Hello, based on the example code of this page, I struggled to implement a read-timeout. Finally I looked into the trust-dns project repository to understand how the "select2" combinator should be used. 

https://gist.github.com/frehberg/1ab4cc3cf98a3188766d20461f6f87bd

I would like to add the code as example, demonstrating read-timeouts and usage of "select2" combinator.

What do you think?

**Comment by carllerche** [comment]
I think it would be good. That said, there will soon be first class timeout support added. Maybe we should wait until that lands (hopefully next week or so).

**Comment by frehberg** [comment]
great news :) this sounds like it might become more ergonomic ;)
Any PR/Issue-Ticket around demonstrating the usage?

**Comment by frehberg** [comment]
Seems to be this task in https://github.com/tokio-rs/tokio/pull/249/commits

**Comment by carllerche** [comment]
Yes! That is the PR.

**Comment by carllerche** [comment]
Closing this issue as the docs are pushed. Let me know your thoughts though!
