### ISSUE TITLE
Going Deeper Futures Mechanics has broken Streams link

### ISSUE THREAD

**Issue by cpick** [tokio-rs/website#168]
content/docs/going-deeper/futures-mechanics.md:10 has a "streams" link that's attempting to point to "../../getting-started/streams-and-sinks", but there's no such file.

The repo does have a "./content/legacy/getting-started/streams-and-sinks.md", but I'm not sure whether teh link should be updated, or if that's so out of date that the link should be removed?

**Comment by carllerche** [comment]
Yeah, the section should be rewritten or at least refreshed. The link could be removed until this happens.
