### ISSUE TITLE
Direct links are getting responded with 403

### ISSUE THREAD

**Issue by pravic** [tokio-rs/website#174]
For example, https://docs.rs/tokio-io/0.1.6/tokio_io/ has a link to https://tokio.rs/docs/getting-started/core/ which responds with 403.

So does https://tokio.rs/docs/getting-started/ and 
https://tokio.rs/docs/

**Comment by pravic** [comment]
Hello?

**Comment by carllerche** [comment]
You are correct. Tokio-io docs should be updated to point to the correct links.

**Comment by carllerche** [comment]
Either that or a redirect could be setup.
