### ISSUE TITLE
Document how to use futures-cpupool with tokio

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/website#18]
I'm not 100% sure if there is a section discussing that tokio-core futures must not perform heavy CPU computation... if there isn't, there should be :)

**Comment by carllerche** [comment]
There is a section here: https://tokio.rs/docs/going-deeper/tasks/#futures-cpupool but I think that a short bit in the architecture doc could be useful.

**Comment by steve-chavez** [comment]
Need as well, an example would be really helpful.

**Comment by carllerche** [comment]
@ivanovaleksey yes, it is to avoid blocking the event loop and yeah, this issue is outdated. I'm going to close it.
