### ISSUE TITLE
Streams link on Essential Combinators links to a 403

### ISSUE THREAD

**Issue by nevi-me** [tokio-rs/website#184]
There's a link on the first paragraph of https://tokio.rs/docs/going-deeper/futures-mechanics/, it points to a 403: https://tokio.rs/docs/getting-started/streams-and-sinks which returns a 403.

I can't figure out if the page doesn't exist, or if the link points to the wrong place.

**Comment by tobz** [comment]
Uh oh!

@carllerche Did we mistakenly delete a page or was it intentional because it got too out of sync with the `futures` API?

**Comment by tobz** [comment]
Oh, woops, looks like you addressed this in #168. :)

@nevi-me Thanks for letting us know!  We'll try and get this taken care of soon.

**Comment by nocduro** [comment]
Also encountered this broken link from this stackoverflow answer:

https://stackoverflow.com/questions/41811075/how-do-i-send-a-list-of-items-through-a-futuressink

Their advice was to read the excellent documentation, but the docs 403 :(

**Comment by nevi-me** [comment]
@nocduro https://web.archive.org/web/20170316062937/https://tokio.rs/docs/getting-started/streams-and-sinks/

Don't know if it's still works, but might help you out in the mean time

**Comment by nocduro** [comment]
Thanks for the archive link, it helps a ton! I'm brand new to futures and streams/sinks, so I've been reading and looking for good introductory docs. The tokio.rs site has been a big help
