### ISSUE TITLE
Building the website is broken locally

### ISSUE THREAD

**Issue by bIgBV** [tokio-rs/website#190]
I'm working on updating the [`impl Trait`](https://tokio.rs/docs/going-deeper/returning/#impl-trait) section of the [returning futures](https://tokio.rs/docs/going-deeper/returning/) page and when I try building the website locally, I get the error:

```
ERROR 2018/08/28 21:59:32 REF_NOT_FOUND: Ref "tasks.md": failed to resolve path from page "/legacy/going-deeper-tokio/core-low-level.md": page reference "tasks.md" is ambiguous
```

[This](https://github.com/tokio-rs/website/blob/master/content/legacy/going-deeper-tokio/core-low-level.md) is the file in question.

**Comment by carllerche** [comment]
You clone the repo, build it, and get that error?

Which version of hugo?

**Comment by bIgBV** [comment]
Yup, it was a right after cloning the repository. 

```
~/P/r/website (update-return-future|…) $ hugo version
Hugo Static Site Generator v0.47.1/extended darwin/amd64 BuildDate: unknown
```

**Comment by carllerche** [comment]
Ah yes, I am on an old version: `Hugo Static Site Generator v0.34 darwin/amd64 BuildDate`

It also looks like CI i using a really old version too: https://github.com/tokio-rs/website/blob/master/.travis.yml#L5

I'm no hugo expert, are you able to look into this? 😄

**Comment by bIgBV** [comment]
Sure thing.
