### ISSUE TITLE
Configure S3 Bucket to Return Custom 404

### ISSUE THREAD

**Issue by rylev** [tokio-rs/website#212]
When a non-existing document is requested, a 403 instead of a 404 is returned. 

Looking at your deploy script I'm guessing you're using AWS S3 for hosting. Here are the docs for setting up a 404 page for S3 websites: https://docs.aws.amazon.com/AmazonS3/latest/dev/CustomErrorDocSupport.html

**Comment by carllerche** [comment]
We just need a 404 page :)
