### ISSUE TITLE
Stop using hard line breaks

### ISSUE THREAD

**Issue by rylev** [tokio-rs/website#230]
The documentation markdown files have a ~80 column limit. While this might be nice for editing, it makes the pages themselves look terrible. We should let the page itself decide when newlines happen.

**Comment by carllerche** [comment]
@rylev could you clarify how this makes the pages look terrible? The line break in MD should not carry over to the rendered content.

**Comment by jasikpark** [comment]
If we *did* want to only use single-line paragraphs, [remark](https://remark.js.org) seems to be a good library/cli for linting markdown and for automatically formatting markdown. Even without the decision to change how linebreaks are done, it still could be useful for it's other style formatting and linting features.

**Comment by jasikpark** [comment]
Another option would be [comrak](https://github.com/kivikakk/comrak), a rust library that does the same.

**Comment by carllerche** [comment]
I'm still not sure that I understand the motivation. What is the problem being solved?

**Comment by jasikpark** [comment]
I don't think that there's a problem being solved by requiring single-line paragraphs, but by having the markdown documents all formatted by an autoformatter, the structure can be easier to see and manage. But it's not necessarily needed.

**Comment by rylev** [comment]
The original reason I opened this issue was because I mistakenly thought the width of the rendered text was contrained by the line breaks in the markdown files (instead of being determined by CSS). I personally think the text width is too small, but this does not have to do with newlines in the markdown files, so I'm closing. @jasikpark If you think having a markdown formatter run over the markdown files, please open another issue. I will open one regarding the width of the text.
