### ISSUE TITLE
Chaining computations example does not compile

### ISSUE THREAD

**Issue by xmclark** [tokio-rs/website#245]
Issue:
The example in "Chaining computations" section in the futures docs does not compile. The `tokio::run` docs suggest that all futures that it runs must have error type `()`.

Expected result:
The example compiles and runs.

Link to docs:
https://tokio.rs/docs/futures/getting_asynchronous/#chaining-computations

Link to playground:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=c67c4a11dc19f37e126fc3f7ced8b793

Link to `tokio::run` docs:
https://docs.rs/tokio/0.1.12/tokio/runtime/fn.run.html

**Comment by carllerche** [comment]
Ah thanks!

This seems like a dup of #254? I happened to see the other one first. Lets continue the discussion there (would be happy to get a PR w/ a fix).
