### ISSUE TITLE
Broken links pointing to tokio 0.1 and 0.2 on docs.rs

### ISSUE THREAD

**Issue by bobrik** [tokio-rs/website#251]
I stumbled upon broken `io:copy` on https://tokio.rs/docs/getting-started/echo/, but then I ran a check and it's definitely not the only occurrence:

![image](https://user-images.githubusercontent.com/89186/48975131-1e6e5600-f01f-11e8-962e-d564763261b8.png)

**Comment by carllerche** [comment]
Yep.... we should try to get CI to check this somehow.

What did you use to run the check?

**Comment by bobrik** [comment]
Good point about doing this in CI.

I googled something like "404 detector" and clicked on the first link:

* https://www.brokenlinkcheck.com/

**Comment by carllerche** [comment]
I googled, it looks like `wget` can be used: https://www.createdbypete.com/articles/simple-way-to-find-broken-links-with-wget/

Would you be able to open a PR that fixes the links and maybe checks the links in CI? :heart:

Roughly:

* `executor/current_thread` -> the `tokio-current-thread` crate.
* `tokio_io`combinators (copy) -> https://docs.rs/tokio/0.1.13/tokio/io/index.html
* tokio-timer links seem to just be wrong (https://docs.rs/tokio-timer/0.2/tokio_timer/timer/struct.Timer.html)
* `Deadline` is now `Timeout`
* All of atokio-core is deprecated... where are those links?
* `tokio-io::codec` is now https://docs.rs/tokio/0.1.13/tokio/codec/index.html
* length_delimited: https://docs.rs/tokio/0.1/tokio/codec/length_delimited/index.html
