### ISSUE TITLE
Getting Asynchronous section has invalid example

### ISSUE THREAD

**Issue by bobrik** [tokio-rs/website#254]
The second example here:

* https://tokio.rs/docs/futures/getting_asynchronous/

If fails to compile with:

```
error[E0271]: type mismatch resolving `<hello::HelloWorld as futures::Future>::Error == ()`
  --> src/hello/mod.rs:43:5
   |
43 |     tokio::run(hello_world)
   |     ^^^^^^^^^^ expected struct `std::io::Error`, found ()
   |
   = note: expected type `std::io::Error`
              found type `()`
   = note: required by `tokio::run`

error: aborting due to 2 previous errors

Some errors occurred: E0271, E0432.
For more information about an error, try `rustc --explain E0271`.
```

Error cannot be non-empty tuple for `tokio::run()`, plus `poll` does not refer to `Self::Error`.

**Comment by carllerche** [comment]
Good point... I wonder why this passed CI.

**Comment by carllerche** [comment]
The `Future` implementation should probably be switched to have a `()` error and all the `try_ready!(...)` bits should have a `map_err(|e| println!(....))` maybe?
