### ISSUE TITLE
I/O With tokio timeline ?

### ISSUE THREAD

**Issue by goriunov** [tokio-rs/website#258]
Hi thanks for you work. I am just wondering when will the next section `I/O With tokio` available at least some approximate timeline :)

**Comment by carllerche** [comment]
Hopefully I'll start writing it within the next few weeks. I'm trying to wrap up some other stuff first.

**Comment by carllerche** [comment]
The section is in progress: https://github.com/tokio-rs/website/pull/260

**Comment by carllerche** [comment]
The first pass as been pushed to tokio.rs. There is a lot more to write, but we would appreciate your feedback in the doc-push repo: http://github.com/tokio-rs/doc-push
