### ISSUE TITLE
hello world example doesnt work on os x without supplying an explicit -p flag to netcat

### ISSUE THREAD

**Issue by jlgerber** [tokio-rs/website#270]
It seems as though netcat requires an explicit -p flag to work, at least on os x Mojave (10.14.1) with netcat version 0.7.1

```
netcat -l -p 6142
```
instead of 
```
netcat -l 6142
```

**Comment by carllerche** [comment]
It looks like netcat isn’t compatible cross platform? There was an issue (#240) that changed the cmd. 

Do you have thoughts on how to make something that works on Mac / Linux / ...?

Ref #240

**Comment by ultrasaurus** [comment]
I tried to repro the error I had earlier, but now I've upgraded my OS to Mojave 10.14.6 and `nc -l -p 6142` is now required (whereas before it had an error)

For the record, details on the version I have installed now which works:
```
nc --version
netcat (The GNU Netcat) 0.7.1
Copyright (C) 2002 - 2003  Giovanni Giacobbi
```

I do think it is helpful to introduce handy networking tools, but maybe we need a section of the docs that covers each tool that we can link to.   (And maybe do something with intro tutorial that is a bit more universal, like an HTTP get or use a different intro example with something more similar across platforms, like telnet.

**Comment by ultrasaurus** [comment]
might be a good idea to side-step this issue and use socat -- https://github.com/tokio-rs/website/pull/393

**Comment by ultrasaurus** [comment]
fixed by switching to socat ( https://github.com/tokio-rs/website/pull/393 )
