### ISSUE TITLE
Examples link at Bottom of Page Returns Github 404

### ISSUE THREAD

**Issue by nazgulsenpai** [tokio-rs/website#324]
The URL linked to Examples at the bottom of the website is https://github.com/tokio-rs/tokio/tree/master/tokio/examples but this produces a Github 404.

**Comment by carllerche** [comment]
Ah, the link should be updated to:  https://github.com/tokio-rs/tokio/tree/v0.1.x/tokio/examples

Would you be able to submit a PR?

**Comment by ultrasaurus** [comment]
looks like someone fixed this!  At least it works for me now, pointing to https://github.com/tokio-rs/tokio/tree/master/examples
