### ISSUE TITLE
rustc complains on sample code

### ISSUE THREAD

**Issue by NickeZ** [tokio-rs/website#34]
https://github.com/tokio-rs/website/blame/master/content/docs/getting-started/pipeline-server.md#L158

```
error[E0053]: method `call` has an incompatible type for trait
   --> src/main.rs:148:5
    |
148 |       fn call(&mut self, input: String) -> Self::Future {
    |  _____^ starting here...
149 | |         future::ok(input).boxed()
150 | |     }
    | |_____^ ...ending here: types differ in mutability
    |
    = note: expected type `fn(&EchoService, std::string::String) -> Box<futures::Future<Error=std::io::Error, Item=std::string::String> + std::marker::Send + 'static>`
    = note:    found type `fn(&mut EchoService, std::string::String) -> Box<futures::Future<Error=std::io::Error, Item=std::string::String> + std::marker::Send + 'static>`

error: aborting due to previous error
```

I fixed it by removing `mut` for self.

**Comment by NickeZ** [comment]
While playing around a little bit I get *really* weird results. I basically have the last example unmodified and I did the following modifications:

```
    fn call(&self, input: String) -> Self::Future {
        let mut copy = String::from("response");
        copy.push_str(input.as_ref());
        copy.push('t');
        future::ok(copy).boxed()
    }
```

But my telnet response are:

```
$ telnet localhost 12345
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
test
tesponsetest
```

Could you explain why it pushes the last `t` to the beginning of the string?

**Comment by alexcrichton** [comment]
The behavior I saw from `nc` locally was that it submitted lines with `\r\n`, and the example server only strips off `\n`. That means that the actual printed value you get back (in terms of bytes) is: `"responsea\rt"`, which renders as you saw locally

**Comment by NickeZ** [comment]
Of course! Thanks
