### ISSUE TITLE
Docs: "why not green threads?"

### ISSUE THREAD

**Issue by steveklabnik** [tokio-rs/website#36]
A lot of people wonder _why_ tokio is made the way that it is. Especially with regards to other languages. It'd be worth having some sort of page that lays out the details here, so that someone can understand the basic design in comparison to others.

For example, there are some things that M:N threads do better than tokio, but those fall afoul of core Rust principles. Discussing this in an even-handed way would be very useful.

**Comment by steveklabnik** [comment]
I feel like @pcwalton could basically knock this out 😉

**Comment by Darksonn** [comment]
Closed in favor of  #452.
