### ISSUE TITLE
make v0.1 doc accessible, without cluttering the experience for latest docs

### ISSUE THREAD

**Issue by ultrasaurus** [tokio-rs/website#371]
There are a lot of tokio users still on 0.1 who need to reference the old docs

Proposal:  Create a branch from before website was updated to 0.2 syntax, deploy that branch with Netlify with different color header

Steps:
- [x] deploy v0.1 branch with Netlify -- https://github.com/tokio-rs/website/pull/396
- [ ] figure out a good hostname (after getting master branch to deploy with Netlify https://github.com/tokio-rs/website/issues/373)
- [x] change current docs to point to v0.1 docs somewhere 

For reference, here's the current navigation:
![image](https://user-images.githubusercontent.com/41906/70184320-7614b800-169c-11ea-9bad-5eec43ac597c.png)

**Comment by ultrasaurus** [comment]
I'm happy to do a PR and instructions on setting up Netlify, if people think this is a good idea.

**Comment by carllerche** [comment]
I do very much :+1:

**Comment by ultrasaurus** [comment]
I've created a branch with the changes for Netlify and custom header color for an "archive" branch. 
My branch is here:  https://github.com/ultrasaurus/website-tokio/tree/v0.1 -- I can't do a PR until the origin branch exists.  I think someone with write access to this repo can do the following steps to make it go live...

1. sign up at https://www.netlify.com/ and approve access to this repo
2. you can leave the build settings mostly blank, since the config is in the `netlify.toml` file (added in later step)
![image](https://user-images.githubusercontent.com/41906/70190258-52f10500-16aa-11ea-9978-8c8337882a97.png)

3. Set up "deploy contexts" with branches you want to build (and this is where to set that builds should happen for pull requests)
![image](https://user-images.githubusercontent.com/41906/70190158-0ad1e280-16aa-11ea-8192-df066a0b7e9f.png)

4.  To create a PR, someone would need to create a `v0.1` branch first.  I *think* we need to branch from https://github.com/tokio-rs/website/commit/6c319a49c3f3264b56fe4c4dbc0fe7781755bf94 to get the latest 0.1 before 0.2 changes started.  Someone with write access to this repo can pull in my changes using command line. 

Something like this:
```
git checkout 6c319a49c3f3264b56fe4c4dbc0fe7781755bf94
git checkout -b v0.1
git remote add ultra https://github.com/ultrasaurus/website-tokio.git
git checkout -b v0.1 ultra/v0.1
git push origin v0.1
```

Then when you push, the build should automatically kick off.  

In the Netlify interface, you can see status by selecting "Deploys" in the menu:
![image](https://user-images.githubusercontent.com/41906/70190536-078b2680-16ab-11ea-8cf3-a02e69c34a45.png)

**Comment by carllerche** [comment]
Branch created [here](https://github.com/tokio-rs/website/tree/v0.1). Netlify is configured.

**Comment by ultrasaurus** [comment]
@carllerche wanna set up a sub-domain?

**Comment by Darksonn** [comment]
What is the status on this with the new website?

**Comment by carllerche** [comment]
At this point, probably less critical. Going to close for now. If someone is still motivated to setup v0-1.tokio.rs they should feel free to do so.
