### ISSUE TITLE
overview content is out of date: futures, async, etc.

### ISSUE THREAD

**Issue by ultrasaurus** [tokio-rs/website#405]
On this page: https://tokio.rs/docs/overview/ 
repo path `content/docs/overview.md`

The following text needs to be rewritten:

in section  **Zero-cost abstractions**

> Tokio is built around [futures]. Futures aren't a new idea, but the way Tokio
uses them is [unique][poll]. Unlike futures from other languages, Tokio's
futures compile down to a state machine. There is no added overhead from
synchronization, allocation, or other costs common with future implementations.

in section  **Modular**

> Tokio leverages [`mio`] for the system event queue and [`futures`] for defining
tasks.  Tokio implements [async] syntax to improve readability of futures.
[Many] libraries are implemented using Tokio, including [`hyper`] and [`actix`].

Note: separate PR to fix links and remove echo example: https://github.com/tokio-rs/website/pull/404

FYI -- I've heard feedback from other Tokio learners that it is confusing whether they need to decide between using futures crate and Rust and I was initially confused as to parts of futures crate was used by Tokio, whether I needed to learn all about it or not.  In think the Modular section would be a great place to explain that kind of thing.

**Comment by LucioFranco** [comment]
1)

> Tokio is built around `std::future::Future`. Futures aren't a new idea but
> the way they are implemented in Rust is unique because of their poll based
> design. Also unlike futures from other languages, Tokio's futures compile down
> to state machines. There is no added overhead from synchronization, allocation,
> or other costs common with future implementations.

2)

> Tokio leverages [mio] for the system event queue and [futures] for defining
> tasks. Tokio takes advantage of async/await to improve readability of futures.
> [Many] libraries are implemented using Tokio, including [hyper] and [actix].

We could prob update the list of projects here too.

Let me know if you like this!

**Comment by ultrasaurus** [comment]
** 1. Zero-cost abstractions **
I think it is super confusing that `std::future::Future` is a Trait defined in std library, but the *implementation* is not.  Isn't Tokio using the futures crate?  if so does it make sense to say "Tokio's futures compile down to state machines."  Isn't tokio using futures crate for futures (I know you say tasks in next paragraph, but I thought that was the main worker part of a future.) . Is it even possible to implement a Future in Rust that wouldn't compile down to a state machine?   (Sorry to bombard you with questions, just trying to illustrate where there's missing info. If I knew these things, I could help write something, but I still have a fairly surface knowledge of much of this stuff)

Maybe there's an analogy that would work.  Is there something else in the std library that is just a Trait and everyone brings their own implementation?  

** 2. Modular **
I like the simple rewrite! Couple of ideas
  -  Maybe mention `reqwest` -- I haven't used it, but people seem to recommend it often and it looks like it uses tokio. 
  - I think @carllerche mentioned that Tokio also uses Streams from Futures crate.  If so, that would be good to mention

**Comment by Darksonn** [comment]
Regarding 1., perhaps call them “Rust's futures” as opposed to “Tokio's Futures”. I also have a snippet that might fit in somewhere:

> Tokio uses the trait `Future` from the standard library to define what an asynchronous task is. The standard library doesn't actually provide any concrete implementations of this trait, nor any way to run them, but having the trait in the standard library provides the entire ecosystem with a common language to speak to each other. 
>
> For example the `futures` crate provides a large collection of tools to combine smaller futures into larger ones, and `tokio` provides futures that can interact with the file system and low-level network details. Similarly `hyper` and `reqwest` build on top of these low-level network tools to build an http library.

Regarding non-state machine futures, the alternatives are:

1. Swapping the call stack.
2. Green threads.
3. Callback hell.

The two first require significant compiler support, so mostly you would have to go for callbacks. But callbacks are fundamentally a push based model, as opposed to Rust's poll based model.

I don't think there are other traits without implementations in std, but `Iterator` is a close analogy. You can think of the `Iterator` situation as if we had the `futures` crate in the standard library (and as if Tokio was a for loop I suppose).

**Comment by Darksonn** [comment]
I'm not quite sure how this fits in with the new guide. Any thoughts?

**Comment by carllerche** [comment]
I think this is mostly "fixed" with the new site. We can open new issues if there are still things.
