### ISSUE TITLE
test install instructions for network utils on Mac, Windows, Unix

### ISSUE THREAD

**Issue by ultrasaurus** [tokio-rs/website#407]
In https://github.com/tokio-rs/website/pull/394, I'm adding a section on network utilities (proposing to change using netcat/telnet)

via @jenmei, maybe we should use `nc` instead of telnet
>  I would suggest using netcat (nc) instead of telnet. I think nc is now more likely to be found on OSes (including Mac OS X) without a separate install. Also, as network code debugging tool, telnet can have some weird side effects (because it's primarily written for the telnet protocol, which is almost, but not quite, plain text; see the Wikipedia page)
> With nc exiting is just ctrl-d so less to read. :-)
> Pretty sure nc is included on Debian and Ubuntu by default, but haven't confirmed.
> nc is included on Mac OS X (telnet has been removed starting with High Sierra).

**Comment by Darksonn** [comment]
We no longer talk about network utilities on the guide.
