### ISSUE TITLE
Document implementing custom future.

### ISSUE THREAD

**Issue by kkimdev** [tokio-rs/website#42]
I think it's good to have a documentation on implementing a custom future.  Especially because the current Future trait API is not exactly intuitive https://github.com/alexcrichton/futures-rs/issues/129.  Let's come up with a good example usecase and document it.

**Comment by aturon** [comment]
Agreed, it'd be great to work through some concrete examples.

An easy route would be to take some of the built-in future combinators and tokio-core primitives, and walk through their implementation.
