### ISSUE TITLE
Document how to store TcpClient in a struct

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/website#43]
The generic params make it a bit tricky.

**Comment by dgriffen** [comment]
I was attempting to store a TcpClient in a struct that used a predefined ClientProto. The struct looked similar to this:
```rust
struct NetClient<D: SomeTrait + 'static> { 
    tcp_client: tokio_proto::TcpClient<Kind, MessageProto<D>>, 
    handle: Handle, 
}
```
It wasn't clear what to put for the type parameter `Kind`. Rust would tell me that it expected the type `tokio_proto::streaming::multiplex::StreamingMultiplex`. But StreamingMultiplex requires its own type parameter that is expected to implement stream.

It seems that as long as I put any stream type that has the proper item and error the code will compile, but this seems entirely counter-intuitive. Surely there should be some type that is correct?
