### ISSUE TITLE
Center "get started" button on mobile

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/website#437]
It is currently aligned to the left.

**Comment by carllerche** [comment]
That's how it was mocked. I don't have much of a thought either way. The text is left-aligned as well. I wonder if left-aligned is easier to read on small screens.

**Comment by peter-donovan** [comment]
Would you like the button to be centered on mobile?

Also, regarding the `hero`, are you opposed to centering the `title` on mobile and justifying the `subtitle` text?

I really think it would look much more consistent. I have already tested it and it does not break the layout.
