### ISSUE TITLE
IDEs

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/website#450]
Apparently CLion needs the following setting to make completion work with Tokio types behind our `impl_*` macros.

Settings > Languages & Frameworks > Rust > Expand declarative macros: Use experimental engine

**Comment by davidbarsky** [comment]
This isn't needed anymore as IntelliJ Rust stabilized the new macro engine: https://blog.jetbrains.com/clion/2020/07/intellij-rust-0-3-new-macro-expansion-engine/
