### ISSUE TITLE
Audit the guides discussing protocols (pipelined / multiplexed) and place emphasis on request / response

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/website#46]
I believe that currently most guides discussing protocols take the fact that they are request / response oriented for granted. We should audit the docs and make sure that this is clarified w/ links to how to work with stream oriented protocols.

That being said "streaming pipelined protocols" vs. "stream oriented" is confusing... maybe we should come up w/ better terminology.

**Comment by Darksonn** [comment]
I am closing this as it is an issue about a guide that no longer exists.
