### ISSUE TITLE
Decrement `rem` in Interval Stream example?

### ISSUE THREAD

**Issue by boxofrox** [tokio-rs/website#467]
Reading through the tutorial for Streams [\[1\]](https://github.com/tokio-rs/website/blob/0a5335181201760a2240c721fc286ca064ca7597/content/tokio/tutorial/streams.md#implementing-stream), the example that implements an `Interval` timer as a `Stream` defines a field for `rem` (remaining?) and checks `rem == 0`, but never decrements the field.

Should there be a decrement after the `rem == 0` check?

\[1]: https://github.com/tokio-rs/website/blob/0a5335181201760a2240c721fc286ca064ca7597/content/tokio/tutorial/streams.md#implementing-stream

**Comment by Darksonn** [comment]
Yeah, this is a mistake.
