### ISSUE TITLE
Include netlify link in footer

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/website#468]
The netlify link was lost when tranistioning to the new website.

**Comment by boxofrox** [comment]
I assume this [\[1\]](https://github.com/tokio-rs/website/commit/81b64da6c16efdcf8c4cddabbdadf7a4d541c728#diff-1578c58a761c0846adb0e788c860a12bR136-R140) is the Netlify link to which you refer?

Do you want to restore the "[Built with love by]..." portion as well?

I can add the Netlify link to the footer below "Stay up to date:" easily enough.  Although, the "Built by" paragraph is long enough to warrant adding another `columns` at the bottom of the footer than spans the half-columns currently in the footer.

\[1\]: https://github.com/tokio-rs/website/commit/81b64da6c16efdcf8c4cddabbdadf7a4d541c728#diff-1578c58a761c0846adb0e788c860a12bR136-R140

**Comment by boxofrox** [comment]
For example, with just the Netlify link.

![image](https://user-images.githubusercontent.com/636691/88726825-63a03080-d0fc-11ea-9750-a12f4ef940a3.png)

**Comment by boxofrox** [comment]
Example 2: Spanning entire footer, centered, with author/contributor credits on mobile device

![image](https://user-images.githubusercontent.com/636691/88728326-710aea00-d0ff-11ea-8e0b-50b6f1d3e2e3.png)

**Comment by Grubba27** [comment]
Hello there!
I've left the links as shown above
![Captura de Tela 2022-02-07 às 23 05 35](https://user-images.githubusercontent.com/70247653/152904084-92eac7b4-da2c-41bf-a7f3-f03570c5deee.png)
_with all 'links' tag_
![Captura de Tela 2022-02-07 às 23 05 57](https://user-images.githubusercontent.com/70247653/152904119-43ef82d3-c96f-44bb-a133-f6111272aeae.png)
_with  only above one's  with 'links' tag_

I could also just leave netlify link as it is with the color as intend maybe ?
I'm opening draft PR for any further adjusment
