### ISSUE TITLE
Wrong claim in the "Async in depth" chapter of the tutorial

### ISSUE THREAD

**Issue by ineol** [tokio-rs/website#532]
In the the [last section](https://tokio.rs/tokio/tutorial/async#a-few-loose-ends) of that chapter, it says:
>  Our earlier implementation did not handle this case and the spawned task would sleep forever, as the wrong task is notified.

However, as far as I can tell, both tasks will be notified since a new thread is spawned every time `poll` is called before the deadline. Empirically, both tasks terminate.

Also, another exposition problem is that the `main` function will terminate before the spawned off task anyway.

**Comment by Darksonn** [comment]
Ah yeah, this is correct. Thanks for spotting it.
