### ISSUE TITLE
The example code in "hello tokio" tutorial page is broken

### ISSUE THREAD

**Issue by mapkts** [tokio-rs/website#553]
The exmaple code in [Hello Tokio](https://tokio.rs/tokio/tutorial/hello-tokio#write-the-code) uses an uncleared crate `bytes`.

```rust
// Set the key "hello" with value "world"
client.set("hello", bytes::Bytes::from("world")).await?;
```

It's best to guide the reader to add the `bytes` crate  in [Add dependencies](https://tokio.rs/tokio/tutorial/hello-tokio#add-dependencies) section in order to succesfully build the example code.

```
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
```

**Comment by Darksonn** [comment]
Maybe we should just revert  #550...
