### ISSUE TITLE
Section Sharded State: Show declaration of variable "db" in code snippets shown for using ShardedDb.

### ISSUE THREAD

**Issue by sateeshkumarb** [tokio-rs/website#576]
In the [Shared State](https://tokio.rs/tokio/tutorial/shared-state) section of the tutorial, in the subsection [Tasks, threads, and contention](https://tokio.rs/tokio/tutorial/shared-state#tasks-threads-and-contention) one of the approaches suggested to address contention is to shard the mutex. The code snippets provided in the tutorial to do so are as below:

```# use std::collections::HashMap;
# use std::sync::{Arc, Mutex};
type ShardedDb = Arc<Vec<Mutex<HashMap<String, Vec<u8>>>>>;
...
...
let shard = db[hash(key) % db.len()].lock().unwrap();
shard.insert(key, value);
```
Though the snippet shows how the shard can be accessed, the snippets doesn't contain declaration of  **db**. The declaration of **db** mentioned examples of the tutorial (till this point) has been: 
```let db = Arc::new(Mutex::new(HashMap::new()))```, 
which I think won't be the same in the sharded context. I think adding declaration of **db** to the code snippet in this section will be helpful.

**Comment by drHuangMHT** [comment]
Same issue, didn't know what to do when first saw those. They could be clearer.
But db should probably be 
```let db = Arc::new(Vec::new(Mutex<HashMap<String,Vec<u8>>>))```
since its type should be ```ShardedDb```

**Comment by Darksonn** [comment]
Actually, you don't want the vector to be empty since you cannot change the length of the vector once you put it in the Arc.
