### ISSUE TITLE
tutorial(Spawning): Unclear "bounded by `'static`" terminology

### ISSUE THREAD

**Issue by joshchoo** [tokio-rs/website#581]
In the [Spawning section](https://tokio.rs/tokio/tutorial/spawning) of the Tokio tutorial, there is the following sentence:

> The link in the info-box above uses the terminology "bounded by 'static" rather than "its type outlives 'static" or "the value is 'static" for T: 'static.

However, the info-box in the tutorial doesn't mention **"bounded by 'static"** anywhere. Rather the info-box states:

> It is a common misconception that 'static always means "lives forever", but this is not the case. Just because a value is 'static does not mean that you have a memory leak. You can read more in Common Rust Lifetime Misconceptions.

It would be clearer to change/clarify the **"bounded by 'static"** to make it more understandable.

**Comment by Darksonn** [comment]
What uses the terminology "bounded by" is the article behind the link in the infobox.

**Comment by joshchoo** [comment]
Ah, I understand now. Thank you for making it clear!
