### ISSUE TITLE
Add developer tooling to enforce consistent code style

### ISSUE THREAD

**Issue by peter-donovan** [tokio-rs/website#599]
I am currently working on a feature for the website and one of the first things that I noticed is that common developer tools are not present.

I am suggesting that some or all of the tools listed below be added to the repository. Along with the list of tools, I have included some of the most compelling reasons to introduce these tools.
  1. [ESLint](https://eslint.org/): JavaScript, TypeScript and React/Next.js files (js,jsx,ts,tsx extensions)
    - Easily configured using a set of common `ESLint` config libraries and plugins
    - Works with existing `Prettier` formatter; `Prettier` rules (conflicting rules can easily be disabled)
    - Helps enforce best practices and/or a custom code style
    - Can help reduce number of bugs and code that leads to unexpected behavior
  2. [Prettier](https://prettier.io/): Opinionated code formatter (already used to some extent in this project)
    - The project already uses `prettier` for formatting
    - A ".prettierrc" config file is more explicit; the current setup uses `Prettier`'s default settings
    - Scripts that use the `Prettier` binary automatically respect the "prettierrc" and ".prettierignore" files
  3. *[Stylelint](https://stylelint.io/): SCSS, CSS, CSS-in-JS stylesheet files and any inline styles
    - Generally recommended; `Stylelint` analyzes _styles_ instead of _code_ (like `ESLint` but for stylesheets)
    - Similar benefits as `ESLint`; assists by making styles easier to read and reason about
    - ***NOTE: Will raise errors within the "styles.scss" file.**
      - These errors can be handled by either ignoring certain rules via the ".stylelintrc.*" config file or by refactoring existing code.
      
This project would greatly benefit from the addition of the first two tools (**ESLint** and **Prettier**). They would not cause any breaking changes as _the linting warnings/errors can be ignored_ (and fine-grained control of linting/formatting is straightforward to achieve).

The biggest advantage is that these tools will help make it easier to maintain the website's existing codebase and easier to add new features if they are needed. They don't add any overhead. They only bring benefits.

The "drawback" to adding dev tooling is that you'll most likely want or need to refactor quite a bit of the codebase. That is, of course, more work. The additional work of refactoring and optimizing the codebase is worth it, though. The code will be more robust, reliable and performant while working the way you expect it to.

I am willing to help in any way that I can (PR's, participating in discussions, refactoring existing code, etc.). I love the `tokio` project and really want to help.

**Comment by Darksonn** [comment]
The quality of the website codebase is somewhat low priority in my eyes, but I would be happy to accept improvements, including the ones you suggest here. We already use linters and formatters in the main Tokio codebase quite extensively.

**Comment by peter-donovan** [comment]
Fair enough. I completely understand why the website is considered low-priority. I am/was just trying to help.

I'll go ahead and close this issue.
Thanks
