### ISSUE TITLE
TLS Error

### ISSUE THREAD

**Issue by gsquire** [tokio-rs/website#6]
Since today is 01/10 I figured I would mention this issue. When I click on https://tokio.rs I get an insecure site warning and then upon proceeding get redirected to a random LinkendIn page.

**Comment by steveklabnik** [comment]
Yes, this isn't set up yet.

**Comment by gsquire** [comment]
Got it. Congratulations on the release! Looking forward to the actual
announcement.

**Comment by carllerche** [comment]
This should be fixed :)
