### ISSUE TITLE
Menu pushes down content on mobile

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/website#61]
Every page in the getting started docs requires scrolling way down. Attached a composite screenshot of what https://tokio.rs/docs/getting-started/tokio/ looks like on my phone with Chrome:

![tokiomobilebug](https://cloud.githubusercontent.com/assets/1023208/21967220/c2f324c0-db50-11e6-997f-4001310f1a88.png)

**Comment by carllerche** [comment]
The top menu is now collapsed, but the second menu is quite long on mobile.

**Comment by Darksonn** [comment]
I am closing this as the new website does not have this issue.
