### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by EdmundsEcho** [tokio-rs/website#624]
Great introduction to the motivation.  It's a thought process that can be applied more generally for my day to day Rust.  Thank you for that.

Here is a small typo I thought that I would point out:

Location:
https://tokio.rs/blog/2021-05-14-inventing-the-service-trait

Paragraph with heading:
"Making Handler more flexible"

In the body:
"Our little Handler trait is working quite nicely, but currently it only supports our HttpRequest and HttpResponse types. It would be nice if those <TYPO HERE>where</TYPO HERE> generic, so users could use whatever type they want."

.. "It would be nice if those *were* generic..."

\- E

**Comment by Darksonn** [comment]
Thanks.
