### ISSUE TITLE
Reference Documentation

### ISSUE THREAD

**Issue by jbendig** [tokio-rs/website#69]
I think it would be helpful to link directly to the reference documentation for the official Tokio crates. Right now you have to do a search on docs.rs or crates.io and potentially filter through many third-party crates to find what you're looking for.

For example, look at the "Documentation" page https://tokio.rs/docs/getting-started/tokio/ . Somewhere in each of the `tokio-proto`, `tokio-core` and `futures` list items there could be links to https://docs.rs/tokio-proto, https://docs.rs/tokio-core, and https://docs.rs/futures respectively.

Another option might be to add links on the left side of the page under a new "Reference" heading.

I'm willing to work on this if there is any interest.

**Comment by alexcrichton** [comment]
Sounds like a great idea to me!
