### ISSUE TITLE
Tokio's tutorial does not mention CancellationToken

### ISSUE THREAD

**Issue by Finomnis** [tokio-rs/website#694]
https://tokio.rs/tokio/topics/shutdown

This example uses an `mpsc` to propagate a shutdown request, while the recommended way of shutting down is [`CancellationToken`](https://docs.rs/tokio-util/latest/tokio_util/sync/struct.CancellationToken.html).

I guess this was because `CancellationToken` wasn't stable enough yet; but after the zero-unsafe rewrite, it should be stable enough now.

## Solution
Adjust the documentation so it mentions `CancellationToken` in the page about shutting down.

**Comment by Darksonn** [comment]
I agree, but the thing it replaces is the "Telling things to shut down" section, and not the part where an mpsc channel is used.

**Comment by Finomnis** [comment]
I agree, my bad. Point stands, though.

**Comment by Darksonn** [comment]
Yes, definitely. Perhaps it would be worth creating a tool to replace the mspc channel as well.

**Comment by Darksonn** [comment]
I opened https://github.com/tokio-rs/tokio/issues/5585 for the mpsc replacement.

**Comment by stanwolverine** [comment]
@Darksonn Does this mean we have to replace [`broadcast channel`](https://docs.rs/tokio/1/tokio/sync/broadcast/index.html) with [`CancellationToken`](https://docs.rs/tokio-util/latest/tokio_util/sync/struct.CancellationToken.html) in "Telling things to shut down" section of the doc?
