### ISSUE TITLE
One page for all API docs

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/website#71]
We've got a whole bunch of crates and rustdoc has lots of support for supporting groups of crates. We should have a hosted version of the documentation with a sidebar that has all the tokio/futures related crates. This should help facilitate exploration of the project, for example.

**Comment by jsgf** [comment]
I also filed https://github.com/onur/docs.rs/issues/116, since it would be nice to have a generic docs.rs fix for this.

**Comment by Darksonn** [comment]
Tokio is no longer split up into many crates, so I am closing this.
