### ISSUE TITLE
Unnecessary async block in tutorial code

### ISSUE THREAD

**Issue by tae-soo-kim** [tokio-rs/website#719]
https://github.com/tokio-rs/website/blob/48e89baca324065d5b608d776dc31f99e5efc1bc/tutorial-code/spawning/src/main.rs#L15C8-L15C8

I am learning Tokio with its tutorial. The tutorial uses an async block which I think is unnecessary:

```rust
tokio::spawn(async move {
    process(socket).await;
});
```

can be simplified into:

```rust
tokio::spawn(process(socket));
```

I'm not quite sure so I opened this issue to confirm this. If this is true, I think it worth explanation in the tutorial. If not, I'd like to know what are the differences between these two.

**Comment by Darksonn** [comment]
Indeed, they are the same.

**Comment by tae-soo-kim** [comment]
Thanks for confirming this. Adding a note in the tutorial could be helpful for readers.
