### ISSUE TITLE
Update Twitter Logo after rebranding

### ISSUE THREAD

**Issue by TheTanay902** [tokio-rs/website#723]
![issue](https://github.com/tokio-rs/website/assets/84577440/4d41c4c9-00cf-42bf-94d2-9f4eaace0a1b)

![image](https://github.com/tokio-rs/website/assets/84577440/13dc6d6a-44b0-452b-9cbf-fd335cd08a28)

The website still uses the old twitter "bird logo" in the header and the footer, in place of the new rebranded "X Logo".

Reference: https://about.twitter.com/en/who-we-are/brand-toolkit

Updating the logo to the relevant icon would be a quick fix, albeit not in need of immediate attention.

**Comment by carllerche** [comment]
Honestly, we probably should remove the twitter logo altogether. We don't post updates there anymore.

**Comment by carllerche** [comment]
On another note, I'll worry more about Twitter branding once they figure it out themselves. The link you included a) does not redirect away from twitter and b) has "About Twitter" in the page title :)

**Comment by TheTanay902** [comment]
@carllerche yeah, it's baffling really, it has the bird logo still for the about pages(for the browser tab), and x.com redirects to twitter.com. In any case, the logo was being updated on some websites so referenced it here -  we can close the issue (and the PR) if the change isn't required presently. Thanks!
