### ISSUE TITLE
Inconsistency of bash scripts in the tutorial

### ISSUE THREAD

**Issue by timKraeuter** [tokio-rs/website#760]
The bash scripts are displayed inconsistently across the tutorial, which is a bit confusing and sometimes less ergonomic when following the tutorial.

# Problem

For example, in [Hello tokio](https://tokio.rs/tokio/tutorial/hello-tokio) and [Spawning](https://tokio.rs/tokio/tutorial/spawning) the following is used (mind the **$**, and language=**bash**):
```text
```bash
$ cargo install mini-redis
```

In [Streams](https://tokio.rs/tokio/tutorial/streams), **$** is used but not language=bash, which is fine but could be changed.

However, later in [Channels](https://tokio.rs/tokio/tutorial/channels), [IO](https://tokio.rs/tokio/tutorial/io), and [Framing](https://tokio.rs/tokio/tutorial/framing) scripts are shown as follows (mind the missing **$**, and language=**text** not bash):

```text
```text
mkdir src/bin
mv src/main.rs src/bin/server.rs
```

This is probably because the commands in Channels, IO, and Framing do not create any output, and without $, multiple commands are easier to copy and paste (more ergonomic).
In contrast, in [Hello tokio](https://tokio.rs/tokio/tutorial/hello-tokio) there is a command with output:

```bash
$ cargo run
got value from the server; result=Some(b"world")
```

# Solutions

Thus, there are multiple solutions:
1. **Use $ consistently**
    * **Less ergonomic** for multiple commands in one block; see the first block in [Hello Tokio](https://tokio.rs/tokio/tutorial/hello-tokio).
2. **Drop $ consistently**
    - **More ergonomic, but commands are less evident due to missing $** Means rewriting the command in [Hello Tokio](https://tokio.rs/tokio/tutorial/hello-tokio) shown above to distinguish commands from output. This is already done at the end of the [Setup](https://tokio.rs/tokio/tutorial/setup) section.
    - We could highlight bash scripts differently (currently, I do not see a difference between text and bash) to distinguish them from other code blocks representing the output (not exactly sure how to do this yet).
3. Leave it as is.

Let me know what you think!

I can draft a pull request for 1 or 2 if you like.

**Comment by Darksonn** [comment]
Thanks for pointing this out. I'm leaning towards consistent use of $.

**Comment by timKraeuter** [comment]
I think that makes the most sense and seems consistent with what I have seen in other documentation.
