### ISSUE TITLE
Unclear how to handle multiple calls to poll in a Future impl

### ISSUE THREAD

**Issue by kw217** [tokio-rs/website#85]
I'm trying to implement the `Future` trait for another type (as it happens, one which implements its own flavour of futures in C). I've followed the documentation in https://tokio.rs/docs/going-deeper-futures/futures-model/ but it's unclear on one point: how exactly should I store the task(s) I receive from `task::current()`?

The documentation currently says
> Blocking a future is a matter of using `park` to get a handle to its task, putting the resulting `Task` in some wakeup queue for the event of interest, and returning `NotReady`.

"In a queue" suggests to me that there might be more than one task in that queue. But just above it says 
> Crucially, though, the task instance stays fixed for the lifetime of the future it is executing—so no allocation is needed to create or install this callback.

So when my `poll` wants to return `NotReady`, should I push the task onto a queue, and arrange to notify all those tasks when I become ready? Or should I keep at most one task, dropping any existing one? I see there's even a method `Task::will_notify_current` - should I check if any of the tasks already on the queue are already current, and only push the current task onto the queue if this is a new one?

Looking at tokio-core's `ScheduledIo` and `TimeoutState` it looks like the intention is that I should simply keep one, i.e., I should store an `Option<Task>` within my object; when my `poll` wants to return `NotReady` I set it to `Some(task::current())`, and when it becomes ready I notify the task if present. Is that right?

It would be great if you could clarify this area of the docs to make it clear how tasks should be handled by futures. Thanks!

**Comment by alexcrichton** [comment]
Oh I think this is definitely a hole in the docs! The intention is that only the *last* task which called `Future::poll` is guaranteed to get woken up. That way futures can cross tasks if need be and wakeups to blockers should always get routed to the right place, accomodating for the fact that there may be spurious wakeups.

Does that make sense? I think `Future::poll` could definitely be updated with this info!

**Comment by kw217** [comment]
Super, thanks. So when my `Future` impl stashes away a task, it should always overwrite the existing one if any? Cool, I'll do that. Yes, it would be good to update the docs to make this clearer.

**Comment by alexcrichton** [comment]
Yeah that should do it! I've filed https://github.com/alexcrichton/futures-rs/issues/515 to improve the docs here.

**Comment by kw217** [comment]
Thanks Alex!
