### ISSUE TITLE
Please make the website font readable

### ISSUE THREAD

**Issue by arystan-sw** [tokio-rs/website#88]
Currently used sans-serif font is very difficult for eyes to read. Additionally, because futures is not so simple subject, this is an obstacle for me as a learner.

From my point of view, the "Source Serif Pro" used in rust api docs would be ok. It can be added by linking to [google fonts].

![screenshot from 2017-06-21 11 40 23](https://user-images.githubusercontent.com/23624737/27368829-84fc0cd0-5676-11e7-8593-fba5b52c4f60.png)

[google fonts]: https://fonts.google.com/specimen/Source+Serif+Pro?selection.family=Source+Serif+Pro

**Comment by nelsonjchen** [comment]
Out of curiousity, what typeface does it eventually render to on your setup? The current typeface CSS rule on `body` heavily favors the system typefaces. 

You can determine this by getting to this GUI:

![screen shot 2017-08-27 at 10 34 12 am](https://user-images.githubusercontent.com/5363/29752466-4e98ec5e-8b13-11e7-916d-8cd4edd9b18a.png)

If the typeface falls all the way back to a system typeface on your setup that's not readable, maybe you can adjust it yourself to Source Serif Pro as the system typeface. It would benefit you more than just on the Tokio.rs site.

**Comment by nelsonjchen** [comment]
Or I guess maybe this site should have Source Serif Pro as the last typeface.

**Comment by carllerche** [comment]
Dunno, I'm pretty sure it is the default bootstrap font list?

**Comment by Darksonn** [comment]
I am closing this as it is an issue about the old website, which no longer exists. If the font on the new website is still unreadable, feel free to open a new issue.
