### ISSUE TITLE
Async database: there is a driver

### ISSUE THREAD

**Issue by P-E-Meunier** [tokio-rs/website#93]
Hi! While teaching a friend about tokio, I read that there was no async database driver yet.
Turns out I wrote one, called pleingres, and used it successfuly for a few months now on nest.pijul.com. May I write a pull request to replace that page with examples using postgres?

**Comment by nelsonjchen** [comment]
One of the aspects of that page I saw which was valuable to me was to demonstrate using pre-existing synchronous code from asynchronous code with the help of thread pools and whatnot. Maybe it should be updated to reference pleingres, but note that the example is intentionally handicapped to demonstrate that kind of usage.

**Comment by kanerogers** [comment]
Agreed with @nelsonjchen - I think it's a good idea to demonstrate async/sync interop.

**Comment by Darksonn** [comment]
I am closing this as it is an issue about a guide that no longer exists.
